[package]
edition = "2021"
name = "memento"
version = "0.1.0"

[[bin]]
name = "memento"
path = "conceptual.rs"

[[bin]]
name = "memento-serde"
path = "serde.rs"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
